/**
 * Orphan adapter-output cleanup.
 *
 * Wave B3 landed `NN-hatch3r-*` precedence-prefixed filenames for per-file
 * rule adapters (cursor, windsurf, copilot, claude, cline). End-user repos
 * upgrading from a pre-B3 hatch3r pick up the new path on `hatch3r sync`,
 * but the old `hatch3r-*.mdc` file remains on disk. Both files then load
 * concurrently in Cursor/Windsurf/Claude/Roo, producing duplicate guidance
 * and (worse) stale guidance.
 *
 * This module provides a deterministic, safety-filtered sweep that unlinks
 * files previously emitted by hatch3r but not emitted by the current
 * adapter set.
 *
 * ## Safety constraints
 *
 * A candidate path is deleted only when ALL of the following hold:
 * 1. The file still exists on disk.
 * 2. Its basename matches `hatch3r-*` or `^\d{2}-hatch3r-*` (the same
 *    dual-prefix recognition used by {@link src/merge/safeWrite.isManagedPath}),
 *    OR it is a `SKILL.md` whose parent directory basename matches those
 *    prefixes (the skill-emission layout `skills/hatch3r-<id>/SKILL.md`;
 *    D10-SA10.6-01).
 * 3. It lives inside a known adapter output root (see
 *    {@link TOOL_PATH_PREFIXES}). In a monorepo (D14-5) the
 *    per-package roots `<pkg>/<prefix>` are also accepted so a removed
 *    package's outputs can be reclaimed; the candidate is still re-validated
 *    against the repo root so this never escapes the project tree.
 * 4. It does NOT carry a `HATCH3R:BEGIN ... END` managed block that wraps
 *    user-authored content mid-file — if only a block is managed, we do
 *    not own the file and we must not unlink it. The BEFORE-block slice is
 *    judged with `isHealableManagedPrefix` (managedBlocks.ts): whitespace or
 *    exactly one generated byte-0 frontmatter stub is hatch3r-owned (the
 *    with-frontmatter skill/command emission shape, release/2.6.0); anything
 *    else before BEGIN, or ANY non-whitespace after END, vetoes the unlink.
 *
 * ## First-run behaviour
 *
 * When `manifest.managedFilesByAdapter[adapter]` is absent, cleanup is a
 * no-op for that adapter: no history means no inferrable orphans. We do
 * NOT attempt to guess orphans from disk alone (that would risk deleting
 * files a prior version of hatch3r never owned).
 *
 * ## Silent Failure Contract
 *
 * Every catch block emits either a structured diagnostic via the returned
 * `OrphanCleanupEntry[]` (with `removed: false` and `error`) or a console
 * warning when the error occurs before per-file bookkeeping is possible
 * (e.g. path-traversal rejection). Callers surface these diagnostics via
 * `warn()` per governance/CONSTITUTION.md §Silent Failure Contract.
 */

import { rmdir } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import {
  isCodexExclusivePath,
  isCodexSharedPath,
  planCodexRemoval,
} from "./codexOwnership.js";
import { acquireWriteLock } from "./safeWrite.js";
import {
  assertRepositoryPathIdentity,
  inspectRepositoryPath,
  normalizeRepositoryRelativePath,
  readRepositoryFileSnapshot,
  readRepositoryPathIdentity,
  removeRepositoryFileIfUnchanged,
  replaceRepositoryFileIfUnchanged,
  type RepositoryFileSnapshot,
  UnsafeRepositoryPathError,
} from "./repositoryPathSafety.js";
import { verbose } from "../cli/shared/ui.js";
import {
  buildAcceptedPrefixes,
  derivePackageRootsFromCandidates,
  diffOrphanCandidates,
  fileContentIsUserWrapped,
  isManagedOutputBasename,
  isPathInKnownAdapterRoot,
  pruneEmptyCodexSkillParents,
  type OrphanCleanupEntry,
} from "./orphanCleanupSupport.js";

export { diffOrphanCandidates } from "./orphanCleanupSupport.js";
export type { OrphanCleanupEntry } from "./orphanCleanupSupport.js";

/**
 * Sweep orphan adapter outputs for one adapter.
 *
 * @param adapter      The adapter tool name (e.g. `"cursor"`).
 * @param rootDir      Absolute path to the repo root.
 * @param previousPaths Paths recorded under `managedFilesByAdapter[adapter]`
 *                     from the prior successful run. Pass `undefined` to
 *                     short-circuit (no history => no orphans).
 * @param currentPaths Paths emitted by the current adapter run. In a monorepo
 *                     this MUST include both root and per-package paths so a
 *                     still-emitted per-package file is not mistaken for an
 *                     orphan (the diff baseline).
 * @param packageRoots Optional monorepo `manifest.packages` paths. When
 *                     present, per-package adapter roots (`<pkg>/<prefix>`) are
 *                     accepted in the containment check so a removed package's
 *                     outputs can be reclaimed (D14-5). Omit / pass `undefined`
 *                     for single-package repos.
 * @param options release/2.8.5 (BUG-3 secondary): `trustedExactPaths` — repo-
 *                relative posix paths allowed to bypass ONLY the
 *                hatch3r-basename filter (filter 2). Callers pass the exact
 *                paths the manifest's `managedFilesByAdapter` recorded for a
 *                DESELECTED adapter, after explicit user consent: provenance
 *                is manifest-recorded, not inferred, so a non-`hatch3r-*`
 *                managed artifact like `CLAUDE.md` can be reclaimed. Every
 *                other safety filter still applies unconditionally — adapter-
 *                root containment (filters 1 + the symlink re-check) and the
 *                user-wrapped veto (filter 4), so a `CLAUDE.md` carrying user
 *                content outside the HATCH3R markers is still refused and
 *                disclosed. The default sync/update sweeps pass no option and
 *                keep the strict basename filter.
 * @returns One entry per candidate, including skipped entries. Empty when
 *          `previousPaths` is undefined/empty.
 */
interface PreparedOrphan {
  relPath: string;
  absPath: string;
  name: string;
  parentDirName: string;
  codexExclusive: boolean;
}

interface OrphanSweepContext {
  adapter: string;
  rootDir: string;
  acceptedPrefixes: readonly string[];
  trustedExactPaths?: ReadonlySet<string>;
}

type PreparedOrphanResult = PreparedOrphan | OrphanCleanupEntry;
type PruneKind = "none" | "codex" | "skill";

function skippedEntry(adapter: string, path: string, reason: OrphanCleanupEntry["reason"]): OrphanCleanupEntry {
  return { adapter, path, removed: false, reason };
}

function candidateNameIsOwned(context: OrphanSweepContext, path: string): boolean {
  const name = basename(path);
  const parent = basename(dirname(path));
  if (isManagedOutputBasename(name, parent)) return true;
  if (context.trustedExactPaths?.has(path.replace(/\\/g, "/"))) return true;
  return context.adapter === "codex" &&
    (isCodexExclusivePath(path) || isCodexSharedPath(path));
}

function prepareOrphanCandidate(context: OrphanSweepContext, candidate: string): PreparedOrphanResult {
  let relPath: string;
  try {
    relPath = normalizeRepositoryRelativePath(candidate);
  } catch (err) {
    verbose(`orphanCleanup: rejected candidate ${JSON.stringify(candidate)} — ${err instanceof Error ? err.message : String(err)}`);
    return skippedEntry(context.adapter, candidate, "outside-adapter-root");
  }
  if (!isPathInKnownAdapterRoot(relPath, context.rootDir, context.acceptedPrefixes)) {
    return skippedEntry(context.adapter, relPath, "outside-adapter-root");
  }
  if (!candidateNameIsOwned(context, relPath)) {
    return skippedEntry(context.adapter, relPath, "not-managed-basename");
  }
  const absPath = resolve(context.rootDir, relPath);
  const root = resolve(context.rootDir);
  const separator = absPath.includes("\\") ? "\\" : "/";
  if (absPath !== root && !absPath.startsWith(root + separator)) {
    return skippedEntry(context.adapter, relPath, "outside-adapter-root");
  }
  return {
    relPath,
    absPath,
    name: basename(relPath),
    parentDirName: basename(dirname(relPath)),
    codexExclusive: context.adapter === "codex" && isCodexExclusivePath(relPath),
  };
}

function snapshotFailureEntry(adapter: string, path: string, err: unknown): OrphanCleanupEntry {
  if ((err as NodeJS.ErrnoException).code === "ENOENT") {
    return skippedEntry(adapter, path, "missing");
  }
  if (err instanceof UnsafeRepositoryPathError && err.reason === "symlink") {
    return skippedEntry(adapter, path, "symlink-skipped");
  }
  return {
    adapter,
    path,
    removed: false,
    reason: "read-failed",
    error: err instanceof Error ? err.message : String(err),
  };
}

async function readInitialOrphanSnapshot(
  context: OrphanSweepContext,
  candidate: PreparedOrphan,
): Promise<RepositoryFileSnapshot | OrphanCleanupEntry> {
  try {
    return await readRepositoryFileSnapshot(context.rootDir, candidate.relPath);
  } catch (err) {
    verbose(`orphanCleanup: snapshot(${candidate.relPath}) skipped — ${err instanceof Error ? err.message : String(err)}`);
    return snapshotFailureEntry(context.adapter, candidate.relPath, err);
  }
}

async function applyCodexOrphanMutation(
  context: OrphanSweepContext,
  candidate: PreparedOrphan,
  snapshot: RepositoryFileSnapshot,
  mutation: { started: boolean },
): Promise<{ entry: OrphanCleanupEntry; prune: PruneKind }> {
  const content = snapshot.content.toString("utf-8");
  const plan = planCodexRemoval(candidate.relPath, candidate.absPath, content, true);
  if (plan.disposition === "foreign") {
    return { entry: skippedEntry(context.adapter, candidate.relPath, "user-wrapped"), prune: "none" };
  }
  mutation.started = true;
  if (plan.disposition === "preserve") {
    await replaceRepositoryFileIfUnchanged(
      context.rootDir, candidate.relPath, snapshot.identity, plan.content,
    );
  } else {
    await removeRepositoryFileIfUnchanged(context.rootDir, candidate.relPath, snapshot.identity);
  }
  return {
    entry: { adapter: context.adapter, path: candidate.relPath, removed: true, reason: "unlinked" },
    prune: plan.disposition === "remove" && candidate.codexExclusive ? "codex" : "none",
  };
}

async function applyGenericOrphanMutation(
  context: OrphanSweepContext,
  candidate: PreparedOrphan,
  snapshot: RepositoryFileSnapshot,
  mutation: { started: boolean },
): Promise<{ entry: OrphanCleanupEntry; prune: PruneKind }> {
  if (fileContentIsUserWrapped(snapshot.content.toString("utf-8"), snapshot.absolutePath)) {
    return { entry: skippedEntry(context.adapter, candidate.relPath, "user-wrapped"), prune: "none" };
  }
  mutation.started = true;
  await removeRepositoryFileIfUnchanged(context.rootDir, candidate.relPath, snapshot.identity);
  const prune = candidate.name === "SKILL.md" &&
    isManagedOutputBasename(candidate.name, candidate.parentDirName) ? "skill" : "none";
  return {
    entry: { adapter: context.adapter, path: candidate.relPath, removed: true, reason: "unlinked" },
    prune,
  };
}

async function pruneGenericSkillParent(rootDir: string, relPath: string): Promise<void> {
  const parentRel = dirname(relPath).replace(/\\/g, "/");
  try {
    const parent = await inspectRepositoryPath(rootDir, parentRel);
    const identity = await readRepositoryPathIdentity(rootDir, parentRel);
    await assertRepositoryPathIdentity(rootDir, parentRel, identity);
    await rmdir(parent.absolutePath);
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    const message = err instanceof Error ? err.message : String(err);
    verbose(code === "ENOTEMPTY"
      ? `orphanCleanup: skill directory ${join(rootDir, parentRel)} left in place — contains other files`
      : `orphanCleanup: rmdir(${join(rootDir, parentRel)}) skipped — ${message}`);
  }
}

async function pruneOrphanParent(rootDir: string, path: string, prune: PruneKind): Promise<void> {
  if (prune === "codex") await pruneEmptyCodexSkillParents(rootDir, path);
  if (prune === "skill") await pruneGenericSkillParent(rootDir, path);
}

async function mutatePreparedOrphan(
  context: OrphanSweepContext,
  candidate: PreparedOrphan,
  initial: RepositoryFileSnapshot,
): Promise<OrphanCleanupEntry> {
  const release = await acquireWriteLock(initial.absolutePath);
  const mutation = { started: false };
  let prune: PruneKind = "none";
  try {
    const snapshot = await readRepositoryFileSnapshot(context.rootDir, candidate.relPath);
    const outcome = context.adapter === "codex"
      ? await applyCodexOrphanMutation(context, candidate, snapshot, mutation)
      : await applyGenericOrphanMutation(context, candidate, snapshot, mutation);
    prune = outcome.prune;
    return outcome.entry;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      return skippedEntry(context.adapter, candidate.relPath, "missing");
    }
    return {
      adapter: context.adapter,
      path: candidate.relPath,
      removed: false,
      reason: mutation.started ? "unlink-failed" : "read-failed",
      error: err instanceof Error ? err.message : String(err),
    };
  } finally {
    await release();
    await pruneOrphanParent(context.rootDir, candidate.relPath, prune);
  }
}

async function processOrphanCandidate(
  context: OrphanSweepContext,
  candidatePath: string,
): Promise<OrphanCleanupEntry> {
  const candidate = prepareOrphanCandidate(context, candidatePath);
  if ("reason" in candidate) return candidate;
  const initial = await readInitialOrphanSnapshot(context, candidate);
  if ("reason" in initial) return initial;
  return mutatePreparedOrphan(context, candidate, initial);
}

export async function sweepOrphansForAdapter(
  adapter: string,
  rootDir: string,
  previousPaths: string[] | undefined,
  currentPaths: Iterable<string>,
  packageRoots?: readonly string[],
  options?: { trustedExactPaths?: ReadonlySet<string> },
): Promise<OrphanCleanupEntry[]> {
  const candidates = diffOrphanCandidates(previousPaths, currentPaths);
  if (candidates.length === 0) return [];
  const allPackageRoots = packageRoots === undefined
    ? undefined
    : [...packageRoots, ...derivePackageRootsFromCandidates(candidates, adapter)];
  const context: OrphanSweepContext = {
    adapter,
    rootDir,
    acceptedPrefixes: buildAcceptedPrefixes(adapter, allPackageRoots),
    trustedExactPaths: options?.trustedExactPaths,
  };
  const results: OrphanCleanupEntry[] = [];
  for (const candidate of candidates) {
    results.push(await processOrphanCandidate(context, candidate));
  }
  return results;
}

/**
 * Format a list of orphan cleanup entries as a human-readable diagnostic
 * suitable for `warn()`. Returns `null` when no diagnostic is warranted
 * (all entries were either `unlinked` or uneventful skips like `missing`).
 * We do surface `user-wrapped` skips — operators should know a planned
 * delete was refused for safety.
 */
export function formatOrphanCleanupDiagnostic(
  entries: OrphanCleanupEntry[],
): string | null {
  if (entries.length === 0) return null;
  const unlinked = entries.filter((e) => e.reason === "unlinked");
  const failed = entries.filter((e) => e.reason === "unlink-failed" || e.reason === "read-failed");
  const safetySkips = entries.filter(
    (e) => e.reason === "user-wrapped" || e.reason === "outside-adapter-root" || e.reason === "not-managed-basename" || e.reason === "symlink-skipped",
  );
  const parts: string[] = [];
  if (unlinked.length > 0) {
    parts.push(
      `Unlinked ${unlinked.length} orphaned adapter output(s) from prior runs: ` +
        unlinked.map((e) => `${e.path} (${e.adapter})`).join(", "),
    );
  }
  if (safetySkips.length > 0) {
    parts.push(
      `Skipped ${safetySkips.length} orphan candidate(s) for safety: ` +
        safetySkips.map((e) => `${e.path} (${e.reason})`).join(", "),
    );
  }
  if (failed.length > 0) {
    parts.push(
      `Failed to remove ${failed.length} orphan candidate(s); remove manually: ` +
        failed.map((e) => `${e.path} (${e.error ?? e.reason})`).join(", "),
    );
  }
  if (parts.length === 0) return null;
  return parts.join(". ");
}

/**
 * Internal helper re-exported for the dirname of relative paths in tests.
 * No runtime consumer outside the cleanup module uses it.
 */
export const _internals = { dirname };
