import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { join, posix } from "node:path";
import { atomicWriteFile } from "../merge/safeWrite.js";

/**
 * Integrity manifest for hatch3r canonical files.
 *
 * **Guarantees:**
 * - Detects unauthorized modifications to hatch3r-managed files (agents, rules, skills, commands, hooks, prompts).
 * - Detects missing or newly added files relative to the last `hatch3r init` or `hatch3r update`.
 * - Manifest-level checksum detects tampering with the integrity file itself.
 *
 * **Limitations:**
 * - Content-addressed only: detects WHAT changed, not WHO or WHEN.
 * - No signing: an attacker with write access can regenerate a valid manifest.
 * - Symlinks are excluded from scanning to prevent symlink-based bypass.
 * - Only scans `.md`, `.mdc`, and `.json` files in designated directories.
 */
export interface IntegrityManifest {
  version: number;
  generated: string;
  hatchVersion: string;
  /** Tool and version that generated this manifest. Present in manifests generated by hatch3r >=1.5.0. */
  generatedBy?: { tool: string; version: string };
  /**
   * D1-SA1.3.2 (High): Adapters the caller intended to run at seal time
   * (the full tool list from hatch.json). Consumers can compare this against
   * `successfulAdapters` to detect partial-failure syncs without needing to
   * re-read hatch.json. Optional for backward compatibility with manifests
   * sealed by hatch3r <1.7.0.
   */
  expectedAdapters?: string[];
  /**
   * D1-SA1.3.2 (High): Adapters that produced outputs successfully during the
   * sync that sealed this manifest. When this set is a proper subset of
   * `expectedAdapters`, the adapter output directories for the missing tools
   * may be stale or absent. Optional for backward compatibility.
   */
  successfulAdapters?: string[];
  files: Record<string, string>;
  checksum: string;
}

/**
 * Options for {@link generateIntegrityManifest} controlling metadata fields
 * that record which adapters the sealing sync attempted and which succeeded.
 */
export interface GenerateIntegrityManifestOptions {
  /** Adapters that were configured to run (from hatch.json tools). */
  expectedAdapters?: string[];
  /** Adapters that produced output successfully during this sync. */
  successfulAdapters?: string[];
  /**
   * G4: When supplied, the previous on-disk manifest is consulted so a
   * regeneration that would produce an identical content fingerprint
   * (same `files` map, same `expectedAdapters`, same `successfulAdapters`)
   * preserves the previous `generated` timestamp instead of stamping a
   * fresh one. This makes `status ↔ sync` idempotent: redundant syncs no
   * longer mask drift on subsequent status runs by overwriting the seal
   * timestamp with a no-op write.
   */
  previousManifest?: IntegrityManifest;
}

export interface VerifyResult {
  file: string;
  status: "pass" | "modified" | "missing" | "new" | "tampered";
  expected?: string;
  actual?: string;
}

/**
 * C9-M16: Discriminated union return shape for {@link verifyIntegrity}.
 *
 * Replaces the legacy `VerifyResult[]` ad-hoc shape with two explicit
 * branches so callers cannot conflate "no manifest" (an empty array under
 * the legacy shape) with "manifest passed" (also a zero-failure array).
 *
 * Branches:
 * - `ok: true` — the manifest exists (or is intentionally absent — see
 *   `manifest === null` case below) and no actionable drift was detected.
 *   `drift` carries the full per-file `VerifyResult[]` so callers that
 *   want to render PASS/NEW rows still have the data.
 * - `ok: false` — actionable drift (modified, missing, or tampered) was
 *   detected. `errors` holds only the actionable rows partitioned by
 *   status; `drift` holds the complete per-file `VerifyResult[]` so
 *   callers can render the full report.
 *
 * `manifest` on the `ok: true` branch is `null` when no `.integrity.json`
 * exists on disk. This preserves the legacy "empty array on no manifest"
 * semantics while making the case explicit at the type level — callers
 * like `add.ts` that intentionally short-circuit on "no manifest" can do
 * so by checking `manifest === null` instead of `results.length === 0`.
 */
export type VerifyIntegrityResult =
  | {
      ok: true;
      /**
       * The manifest that was verified. `null` when no `.integrity.json`
       * exists on disk (treated as a no-op pass for callers that ran
       * `verifyIntegrity` before init/update has sealed the project).
       */
      manifest: IntegrityManifest | null;
      /**
       * Full per-file results. Empty when `manifest === null`. Otherwise
       * carries one entry per file in the manifest (status `pass`) and
       * one entry per new file on disk (status `new`).
       */
      drift: VerifyResult[];
    }
  | {
      ok: false;
      /**
       * Actionable drift rows partitioned by status. A row appears in
       * exactly one of these arrays. `tampered` covers the manifest-level
       * checksum mismatch (single row, file = `.integrity.json`).
       */
      errors: {
        modified: VerifyResult[];
        missing: VerifyResult[];
        tampered: VerifyResult[];
      };
      /**
       * Full per-file results, including `pass` and `new` rows alongside
       * the actionable drift. Callers that want to render a complete
       * report (e.g. `hatch3r verify` printing every row) read from here.
       */
      drift: VerifyResult[];
    };

const INTEGRITY_FILE = ".integrity.json";
/**
 * Directories scanned for canonical content hashing.
 *
 * C9-H2 (D2-SA2.7-01): Adds `policy`, `learnings`, `checks`, and `user` so
 * tamper detection covers every canonical subtree the framework ships and
 * the project mounts. Previously these subtrees were silently excluded —
 * a file under `.agents/policy/` could be modified without `verify`
 * surfacing a `modified` result. Tracked by a CI assertion in
 * `src/__tests__/integrity/index.test.ts`.
 */
export const SCANNED_DIRS = [
  "agents",
  "commands",
  "rules",
  "skills",
  "hooks",
  "prompts",
  "github-agents",
  "mcp",
  "checks",
  "policy",
  "learnings",
  "user",
];

/** Compute a SHA-256 hash of a UTF-8 string, prefixed with `sha256:`. */
function sha256(content: string): string {
  return `sha256:${createHash("sha256").update(content, "utf-8").digest("hex")}`;
}

/**
 * C9-H3 (D2-SA2.7-02): Stable JSON serialisation of a string→string map
 * with keys sorted lexicographically. `JSON.stringify` preserves insertion
 * order, which is filesystem-dependent for objects whose keys came from
 * `readdir`. Sorting yields the same byte sequence across macOS APFS and
 * Linux ext4/xfs for identical content.
 */
function canonicalStringify(files: Record<string, string>): string {
  const keys = Object.keys(files).sort();
  const parts: string[] = [];
  for (const key of keys) {
    parts.push(`${JSON.stringify(key)}:${JSON.stringify(files[key])}`);
  }
  return `{${parts.join(",")}}`;
}

/** Recursively collect `.md`, `.mdc`, and `.json` file paths from a directory, skipping symlinks. */
async function collectFiles(dir: string, base: string): Promise<string[]> {
  const files: string[] = [];
  let entries: { name: string; isDirectory: () => boolean; isFile: () => boolean; isSymbolicLink: () => boolean }[];
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return files;
    throw err;
  }
  for (const entry of entries) {
    if (entry.isSymbolicLink()) continue;
    const fullPath = join(dir, entry.name);
    const relPath = posix.join(base, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(fullPath, relPath)));
    } else if (entry.isFile() && (entry.name.endsWith(".md") || entry.name.endsWith(".mdc") || entry.name.endsWith(".json"))) {
      files.push(relPath);
    }
  }
  return files;
}

/**
 * Generate an integrity manifest by hashing all canonical files in the .agents directory.
 *
 * Scans `.md`, `.mdc`, and `.json` files in designated subdirectories
 * and produces a SHA-256 hash for each. The manifest-level checksum
 * covers the entire file hash map to detect tampering.
 *
 * Optionally records which adapters the caller expected to run
 * (`expectedAdapters`) and which succeeded (`successfulAdapters`) so that
 * downstream tools (`hatch3r status`, `hatch3r verify`) can detect
 * partial-failure syncs without re-reading `hatch.json`.
 */
export async function generateIntegrityManifest(
  agentsDir: string,
  hatchVersion: string,
  options: GenerateIntegrityManifestOptions = {},
): Promise<IntegrityManifest> {
  const files: Record<string, string> = {};

  for (const dir of SCANNED_DIRS) {
    const dirPath = join(agentsDir, dir);
    const mdFiles = await collectFiles(dirPath, dir);
    for (const relPath of mdFiles) {
      const content = await readFile(join(agentsDir, relPath), "utf-8");
      files[relPath] = sha256(content);
    }
  }

  // C9-H3 (D2-SA2.7-02): Stringify with keys sorted so the manifest-level
  // checksum is filesystem-order independent. Without the sort, macOS APFS
  // (case-insensitive, default-ordered) and Linux ext4/xfs (insertion-ordered
  // by readdir) produce different `JSON.stringify(files)` byte sequences on
  // identical content, yielding divergent checksums. Sorting the input is
  // cheaper than canonicalising the object after the fact.
  const checksum = createHash("sha256")
    .update(canonicalStringify(files))
    .digest("hex");

  const expectedAdapters = options.expectedAdapters
    ? [...options.expectedAdapters].sort()
    : undefined;
  const successfulAdapters = options.successfulAdapters
    ? [...options.successfulAdapters].sort()
    : undefined;

  // G4: When the new content fingerprint matches the previous manifest's
  // fingerprint exactly (same files map by relative path + hash, same
  // expected/successful adapter sets, same hatchVersion), return the
  // previous manifest unchanged so the `generated` timestamp survives.
  // This prevents a redundant sync from masking drift on the next status
  // run by stamping a fresh seal time on identical content.
  if (options.previousManifest) {
    const prev = options.previousManifest;
    if (
      prev.checksum === checksum &&
      prev.hatchVersion === hatchVersion &&
      adapterSetsEqual(prev.expectedAdapters, expectedAdapters) &&
      adapterSetsEqual(prev.successfulAdapters, successfulAdapters) &&
      filesMapEqual(prev.files, files)
    ) {
      return prev;
    }
  }

  const manifest: IntegrityManifest = {
    version: 1,
    generated: new Date().toISOString(),
    hatchVersion,
    generatedBy: { tool: "hatch3r", version: hatchVersion },
    files,
    checksum,
  };

  if (expectedAdapters) {
    // Deterministic sort so semantically-equivalent syncs produce identical
    // manifests (aids diffing and test assertions).
    manifest.expectedAdapters = expectedAdapters;
  }
  if (successfulAdapters) {
    manifest.successfulAdapters = successfulAdapters;
  }

  return manifest;
}

/** True when two optional sorted string arrays denote the same set. */
function adapterSetsEqual(
  a: string[] | undefined,
  b: string[] | undefined,
): boolean {
  if (a === undefined && b === undefined) return true;
  if (a === undefined || b === undefined) return false;
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

/** True when two relative-path -> hash maps have identical entries. */
function filesMapEqual(
  a: Record<string, string>,
  b: Record<string, string>,
): boolean {
  const aKeys = Object.keys(a);
  const bKeys = Object.keys(b);
  if (aKeys.length !== bKeys.length) return false;
  for (const key of aKeys) {
    if (a[key] !== b[key]) return false;
  }
  return true;
}

/** Atomically write the integrity manifest to `.agents/.integrity.json`. */
export async function writeIntegrityManifest(
  agentsDir: string,
  manifest: IntegrityManifest,
): Promise<void> {
  const filePath = join(agentsDir, INTEGRITY_FILE);
  await atomicWriteFile(filePath, JSON.stringify(manifest, null, 2) + "\n");
}

/** Runtime type guard that validates an unknown value conforms to the IntegrityManifest shape. */
function validateIntegrityManifest(data: unknown): data is IntegrityManifest {
  if (typeof data !== "object" || data === null) return false;
  const obj = data as Record<string, unknown>;
  if (typeof obj.version !== "number") return false;
  if (typeof obj.generated !== "string") return false;
  if (typeof obj.hatchVersion !== "string") return false;
  // generatedBy is required in new manifests but tolerated absent for backward compat
  if (obj.generatedBy !== undefined) {
    if (typeof obj.generatedBy !== "object" || obj.generatedBy === null) return false;
    const gb = obj.generatedBy as Record<string, unknown>;
    if (typeof gb.tool !== "string" || typeof gb.version !== "string") return false;
  }
  // D1-SA1.3.2: expectedAdapters/successfulAdapters are optional string arrays.
  // Validate when present so malformed values do not silently coerce to `any`.
  if (obj.expectedAdapters !== undefined) {
    if (!Array.isArray(obj.expectedAdapters)) return false;
    for (const v of obj.expectedAdapters) {
      if (typeof v !== "string") return false;
    }
  }
  if (obj.successfulAdapters !== undefined) {
    if (!Array.isArray(obj.successfulAdapters)) return false;
    for (const v of obj.successfulAdapters) {
      if (typeof v !== "string") return false;
    }
  }
  if (typeof obj.files !== "object" || obj.files === null) return false;
  for (const val of Object.values(obj.files as Record<string, unknown>)) {
    if (typeof val !== "string") return false;
  }
  if (typeof obj.checksum !== "string") return false;
  return true;
}

/** Read and validate the integrity manifest, returning null if absent or malformed. */
export async function readIntegrityManifest(
  agentsDir: string,
): Promise<IntegrityManifest | null> {
  try {
    const raw = await readFile(join(agentsDir, INTEGRITY_FILE), "utf-8");
    const parsed: unknown = JSON.parse(raw);
    if (!validateIntegrityManifest(parsed)) return null;
    return parsed;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    if (err instanceof SyntaxError) return null;
    throw err;
  }
}

/**
 * Verify integrity of all canonical files against the stored manifest.
 *
 * C9-M16: Returns a {@link VerifyIntegrityResult} discriminated union so
 * callers cannot conflate "no manifest" with "manifest passed". The
 * `ok: true` branch carries the verified manifest (or `null` when no
 * manifest exists on disk) and the full per-file `drift` array; the
 * `ok: false` branch partitions the actionable drift rows (`modified`,
 * `missing`, `tampered`) under `errors` while preserving the complete
 * per-file report under `drift`.
 *
 * Per-file row statuses: `pass`, `modified`, `missing`, `new`, or
 * `tampered`. A tampered manifest is reported as a single row on the
 * `.integrity.json` path with `status === "tampered"`.
 */
export async function verifyIntegrity(
  agentsDir: string,
): Promise<VerifyIntegrityResult> {
  const manifest = await readIntegrityManifest(agentsDir);
  if (!manifest) {
    return { ok: true, manifest: null, drift: [] };
  }

  // C9-H3: Recompute with the same canonical (sorted-key) stringifier so
  // verifyIntegrity stays cross-OS reproducible.
  const expectedChecksum = createHash("sha256")
    .update(canonicalStringify(manifest.files))
    .digest("hex");
  if (manifest.checksum !== expectedChecksum) {
    const tamperedRow: VerifyResult = { file: INTEGRITY_FILE, status: "tampered" };
    return {
      ok: false,
      errors: { modified: [], missing: [], tampered: [tamperedRow] },
      drift: [tamperedRow],
    };
  }

  const results: VerifyResult[] = [];
  const manifestFiles = new Set(Object.keys(manifest.files));

  for (const [filePath, expectedHash] of Object.entries(manifest.files)) {
    const fullPath = join(agentsDir, filePath);
    try {
      const content = await readFile(fullPath, "utf-8");
      const actualHash = sha256(content);
      if (actualHash === expectedHash) {
        results.push({ file: filePath, status: "pass" });
      } else {
        results.push({
          file: filePath,
          status: "modified",
          expected: expectedHash,
          actual: actualHash,
        });
      }
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") {
        results.push({
          file: filePath,
          status: "missing",
          expected: expectedHash,
        });
      } else {
        throw err;
      }
    }
  }

  for (const dir of SCANNED_DIRS) {
    const dirPath = join(agentsDir, dir);
    const onDisk = await collectFiles(dirPath, dir);
    for (const filePath of onDisk) {
      if (!manifestFiles.has(filePath)) {
        const content = await readFile(join(agentsDir, filePath), "utf-8");
        results.push({
          file: filePath,
          status: "new",
          actual: sha256(content),
        });
      }
    }
  }

  results.sort((a, b) => a.file.localeCompare(b.file));

  // C9-M16: Partition actionable drift rows so callers can branch on
  // `ok: false` without re-filtering. `new` rows are advisory (a fresh
  // canonical file appeared on disk) and do not count as drift.
  const modified = results.filter((r) => r.status === "modified");
  const missing = results.filter((r) => r.status === "missing");
  const hasDrift = modified.length > 0 || missing.length > 0;

  if (!hasDrift) {
    return { ok: true, manifest, drift: results };
  }

  return {
    ok: false,
    errors: { modified, missing, tampered: [] },
    drift: results,
  };
}
