import type { HookDefinition } from "../hooks/types.js";
import type { AdapterOutput } from "../types.js";
import { wrapManagedFor } from "../merge/managedBlocks.js";
import {
  codexHookCommand,
  codexHookCommandWindows,
} from "../codex/hookOwnership.js";
import {
  CODEX_HOOK_SUPPORT_DIR,
  codexHooksError,
  OWNERSHIP_PREFIX,
  SAFE_HOOK_ID_RE,
  type CodexCommandHookHandler,
  type CodexHookEvent,
  type CodexHookGroup,
} from "./codexHookTypes.js";

export {
  codexHookCommand,
  codexHookCommandWindows,
  codexHookOwnershipId,
} from "../codex/hookOwnership.js";

export interface MappedCodexHook {
  id: string;
  event: CodexHookEvent;
  group: CodexHookGroup;
  output: AdapterOutput;
}

function compareHookIds(left: MappedCodexHook, right: MappedCodexHook): number {
  return left.id < right.id ? -1 : left.id > right.id ? 1 : 0;
}

function supportPath(id: string): string {
  return `${CODEX_HOOK_SUPPORT_DIR}/hatch3r-${id}.mjs`;
}

function generatedHandler(id: string): CodexCommandHookHandler {
  return {
    type: "command",
    command: codexHookCommand(id),
    commandWindows: codexHookCommandWindows(id),
    timeout: 5,
    statusMessage: `${OWNERSHIP_PREFIX}${id}`,
    additionalContextLimit: 4096,
    async: false,
  };
}

function supportScript(hook: HookDefinition): string {
  const instruction =
    `hatch3r hook bridge (${hook.id}): delegate this task to the hatch3r-${hook.agent} custom subagent. ` +
    "If subagent delegation is unavailable, follow the equivalent repository instructions and report the result in plain text.";
  return [
    "// Generated by hatch3r. This command emits context only; it performs no repository mutation.",
    `process.stdout.write(${JSON.stringify(instruction + "\n")});`,
  ].join("\n");
}

function mapSessionHook(hook: HookDefinition): MappedCodexHook {
  if (!SAFE_HOOK_ID_RE.test(hook.id)) {
    throw codexHooksError(`Canonical hook id "${hook.id}" is unsafe for Codex projection.`);
  }
  const scriptBody = supportScript(hook);
  const path = supportPath(hook.id);
  return {
    id: hook.id,
    event: "SessionStart",
    group: { hooks: [generatedHandler(hook.id)] },
    output: {
      path,
      content: wrapManagedFor(path, scriptBody),
      managedContent: scriptBody,
      action: "create",
      sourceFiles: hook.sourcePath ? [hook.sourcePath] : [],
    },
  };
}

export function mapCodexHooks(
  hooks: readonly HookDefinition[],
  warnings: string[],
): MappedCodexHook[] {
  const mapped: MappedCodexHook[] = [];
  for (const hook of hooks) {
    if (hook.event === "session-start") {
      mapped.push(mapSessionHook(hook));
      continue;
    }
    warnings.push(
      `[codex] Hook "${hook.id}" (${hook.event}) is unsupported: Codex has no equivalent event with the same lifecycle semantics; no handler was emitted.`,
    );
  }
  return mapped.sort(compareHookIds);
}
