import { join } from "node:path";
import chalk from "chalk";
import { printBanner, error as logError, info, warn } from "../shared/ui.js";
import { AGENTS_DIR, HatchError } from "../../types.js";
import { verifyIntegrity } from "../../integrity/index.js";

/**
 * Refuse to proceed when canonical files have drifted unless `--force` is set.
 *
 * C7-H5 (D15, OWASP ASI 2026): All mutation commands (init/sync/update/add)
 * must run a preflight integrity check so silent tampering is not amplified
 * downstream. Centralised here so future `add` work uses the same guard.
 */
async function preflightIntegrityCheck(rootDir: string, force: boolean): Promise<void> {
  const agentsDir = join(rootDir, AGENTS_DIR);
  const results = await verifyIntegrity(agentsDir);
  if (results.length === 0) return; // No manifest yet — nothing to verify.

  const modified = results.filter((r) => r.status === "modified");
  const missing = results.filter((r) => r.status === "missing");
  const tampered = results.filter((r) => r.status === "tampered");
  const driftDetected = modified.length > 0 || missing.length > 0 || tampered.length > 0;
  if (!driftDetected) return;

  warn("Integrity issues detected before add:");
  for (const r of tampered) warn(`  TAMPERED: ${r.file}`);
  for (const r of modified) warn(`  MODIFIED: ${r.file}`);
  for (const r of missing) warn(`  MISSING:  ${r.file}`);

  if (!force) {
    logError(
      "Refusing to add with integrity drift. Run `hatch3r verify` to inspect, " +
      "or re-run with --force to proceed.",
    );
    throw new HatchError(
      "Integrity drift detected (use --force to override)",
      1,
      "INTEGRITY_ERROR",
    );
  }
  warn("Continuing with --force: drifted files will not be regenerated by `add`.");
  console.log();
}

export async function addCommand(opts: { force?: boolean } = {}): Promise<void> {
  printBanner(true);
  // C7-H5 (D15): Preflight integrity check runs before any future mutation
  // logic in this command, even though the body currently exits early with
  // an informational "coming soon" notice. When the command is wired up, the
  // guard is already in place — no second pass required.
  await preflightIntegrityCheck(process.cwd(), !!opts.force);

  // C8-D1-M8 (D1-SA1.3.1, P1): `hatch3r add` is advertised in `--help` as a
  // community-pack installer that is not yet shipped. Exiting with code 2
  // (usage error per Bash/sysexits) misrepresents a valid invocation as user
  // misuse and trips CI pipelines that probe the subcommand. Return cleanly
  // (exit 0) with an informational notice plus a roadmap pointer — this
  // satisfies P1 actionable-error guidance (the user has an action: track
  // the repo's releases / discussions) without pretending the feature is
  // done.
  //
  // Sources re-verified 2026-04-20:
  //   - https://tldp.org/LDP/abs/html/exitcodes.html (exit 2 = Bash misuse)
  //   - https://man.freebsd.org/cgi/man.cgi?query=sysexits (EX_OK = 0)
  console.log();
  info("Community pack installation is coming in a future hatch3r release.");
  console.log(chalk.dim("  Track progress: https://github.com/hatch3r/hatch3r/releases"));
  console.log(chalk.dim("  Discuss packs:  https://github.com/hatch3r/hatch3r/discussions"));
  console.log();
}
